package model;
// Generated Apr 13, 2017 11:31:40 PM by Hibernate Tools 4.3.1



/**
 * Cost generated by hbm2java
 */
public class Cost  implements java.io.Serializable {


     private int costId;
     private User user;
     private String CCategory;
     private String CDetails;
     private String UName;
     private Double CAmount;

    public Cost() {
    }

	
    public Cost(int costId, User user, String CCategory) {
        this.costId = costId;
        this.user = user;
        this.CCategory = CCategory;
    }
    public Cost(int costId, User user, String CCategory, String CDetails, String UName, Double CAmount) {
       this.costId = costId;
       this.user = user;
       this.CCategory = CCategory;
       this.CDetails = CDetails;
       this.UName = UName;
       this.CAmount = CAmount;
    }
   
    public int getCostId() {
        return this.costId;
    }
    
    public void setCostId(int costId) {
        this.costId = costId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getCCategory() {
        return this.CCategory;
    }
    
    public void setCCategory(String CCategory) {
        this.CCategory = CCategory;
    }
    public String getCDetails() {
        return this.CDetails;
    }
    
    public void setCDetails(String CDetails) {
        this.CDetails = CDetails;
    }
    public String getUName() {
        return this.UName;
    }
    
    public void setUName(String UName) {
        this.UName = UName;
    }
    public Double getCAmount() {
        return this.CAmount;
    }
    
    public void setCAmount(Double CAmount) {
        this.CAmount = CAmount;
    }




}


