package model;
// Generated Apr 13, 2017 11:31:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userId;
     private String UName;
     private String UEmail;
     private String UPass;
     private Integer UAge;
     private String UPhone;
     private String UAddress;
     private Set costs = new HashSet(0);

    public User() {
    }

    public User(String UName, String UEmail, String UPass, Integer UAge, String UPhone, String UAddress, Set costs) {
       this.UName = UName;
       this.UEmail = UEmail;
       this.UPass = UPass;
       this.UAge = UAge;
       this.UPhone = UPhone;
       this.UAddress = UAddress;
       this.costs = costs;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUName() {
        return this.UName;
    }
    
    public void setUName(String UName) {
        this.UName = UName;
    }
    public String getUEmail() {
        return this.UEmail;
    }
    
    public void setUEmail(String UEmail) {
        this.UEmail = UEmail;
    }
    public String getUPass() {
        return this.UPass;
    }
    
    public void setUPass(String UPass) {
        this.UPass = UPass;
    }
    public Integer getUAge() {
        return this.UAge;
    }
    
    public void setUAge(Integer UAge) {
        this.UAge = UAge;
    }
    public String getUPhone() {
        return this.UPhone;
    }
    
    public void setUPhone(String UPhone) {
        this.UPhone = UPhone;
    }
    public String getUAddress() {
        return this.UAddress;
    }
    
    public void setUAddress(String UAddress) {
        this.UAddress = UAddress;
    }
    public Set getCosts() {
        return this.costs;
    }
    
    public void setCosts(Set costs) {
        this.costs = costs;
    }

    public User(Integer userId, String UName, String UEmail, String UPass, Integer UAge, String UPhone, String UAddress) {
        this.userId = userId;
        this.UName = UName;
        this.UEmail = UEmail;
        this.UPass = UPass;
        this.UAge = UAge;
        this.UPhone = UPhone;
        this.UAddress = UAddress;
    }

    public User(String UName, String UEmail, String UPass, Integer UAge, String UPhone, String UAddress) {
        this.UName = UName;
        this.UEmail = UEmail;
        this.UPass = UPass;
        this.UAge = UAge;
        this.UPhone = UPhone;
        this.UAddress = UAddress;
    }




}


